before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y autoconf automake
language: c
compiler: gcc
script: aclocal && autoconf && automake --add-missing --copy && ./configure && make && make check
